#include QMK_KEYBOARD_H

enum custom_keycodes {
    GRVA = SAFE_RANGE,
    GRVE,
    GRVU,
    CIRA,
    CIRO,
    CIRE,
    CIRU,
    CIRI,
    UMLE,
    UMLU,
    UMLI,
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
    case GRVA:
        if (record->event.pressed) {
        SEND_STRING(SS_RALT("`")"a");
        }
        break;
    case GRVE:
        if (record->event.pressed) {
        SEND_STRING(SS_RALT("`")"e");
        }
        break;
    case GRVU:
        if (record->event.pressed) {
        SEND_STRING(SS_RALT("`")"u");
        }
        break;
    case CIRA:
        if (record->event.pressed) {
        SEND_STRING(SS_RALT("6")"a");
        }
        break;
    case CIRO:
        if (record->event.pressed) {
        SEND_STRING(SS_RALT("6")"o");
        }
        break;
    case CIRE:
        if (record->event.pressed) {
        SEND_STRING(SS_RALT("6")"e");
        }
        break;
    case CIRU:
        if (record->event.pressed) {
        SEND_STRING(SS_RALT("6")"u");
        }
        break;
    case CIRI:
        if (record->event.pressed) {
        SEND_STRING(SS_RALT("6")"i");
        }
        break;
    case UMLE:
        if (record->event.pressed) {
          SEND_STRING(SS_RALT(SS_RSFT("\""))"e");
        }
        break;
    case UMLU:
        if (record->event.pressed) {
          SEND_STRING(SS_RALT(SS_RSFT("\""))"u");
        }
        break;
    case UMLI:
        if (record->event.pressed) {
          SEND_STRING(SS_RALT(SS_RSFT("\""))"i");
        }
        break;
    }
    return true;
};

enum combos { 
  L1C,
  L1S,
  L1G,
  L1A,
  L2C,
  L2S,
  L2G,
  L2A,
  L1CS,
  L1GS,
  L2CS,
  L2GS,
  L3ACUE,
  L3GRVA,
  L3GRVE,
  L3GRVU,
  L3CIRA,
  L3CIRO,
  L3CIRE,
  L3CIRU,
  L3CIRI,
  L3UMLE,
  L3UMLU,
  L3UMLI,
  L3CEDC,
};

const uint16_t PROGMEM l1c[] = { OSL(2), KC_U, COMBO_END};
const uint16_t PROGMEM l1s[] = { OSL(2), KC_E, COMBO_END};
const uint16_t PROGMEM l1g[] = { OSL(2), KC_O, COMBO_END};
const uint16_t PROGMEM l1a[] = { OSL(2), KC_A, COMBO_END};
const uint16_t PROGMEM l2c[] = { OSL(1), KC_H, COMBO_END};
const uint16_t PROGMEM l2s[] = { OSL(1), KC_T, COMBO_END};
const uint16_t PROGMEM l2g[] = { OSL(1), KC_N, COMBO_END};
const uint16_t PROGMEM l2a[] = { OSL(1), KC_S, COMBO_END};
const uint16_t PROGMEM l1cs[] = { OSL(2), KC_E, KC_U, COMBO_END};
const uint16_t PROGMEM l1gs[] = { OSL(2), KC_E, KC_O, COMBO_END};
const uint16_t PROGMEM l2cs[] = { OSL(1), KC_T, KC_H, COMBO_END};
const uint16_t PROGMEM l2gs[] = { OSL(1), KC_T, KC_N, COMBO_END};
const uint16_t PROGMEM l3acue[] = { OSL(3), KC_O, COMBO_END};
const uint16_t PROGMEM l3grva[] = { OSL(3), KC_A, COMBO_END};
const uint16_t PROGMEM l3grve[] = { OSL(3), KC_E, COMBO_END};
const uint16_t PROGMEM l3grvu[] = { OSL(3), KC_U, COMBO_END};
const uint16_t PROGMEM l3cira[] = { OSL(3), KC_QUOT, COMBO_END};
const uint16_t PROGMEM l3ciro[] = { OSL(3), KC_COMM, COMBO_END};
const uint16_t PROGMEM l3cire[] = { OSL(3), KC_DOT, COMBO_END};
const uint16_t PROGMEM l3ciru[] = { OSL(3), KC_P, COMBO_END};
const uint16_t PROGMEM l3ciri[] = { OSL(3), KC_Y, COMBO_END};
const uint16_t PROGMEM l3umle[] = { OSL(3), KC_J, COMBO_END};
const uint16_t PROGMEM l3umlu[] = { OSL(3), KC_K, COMBO_END};
const uint16_t PROGMEM l3umli[] = { OSL(3), KC_X, COMBO_END};
const uint16_t PROGMEM l3cedc[] = { OSL(3), KC_C, COMBO_END};

combo_t key_combos[COMBO_COUNT] = {
  [L1C] = COMBO(l1c, OSM(MOD_LCTL)),
  [L1S] = COMBO(l1s, OSM(MOD_LSFT)),
  [L1G] = COMBO(l1g, OSM(MOD_LGUI)),
  [L1A] = COMBO(l1a, OSM(MOD_LALT)),
  [L2C] = COMBO(l2c, OSM(MOD_RCTL)),
  [L2S] = COMBO(l2s, OSM(MOD_RSFT)),
  [L2G] = COMBO(l2g, OSM(MOD_RGUI)),
  [L2A] = COMBO(l2a, OSM(MOD_RALT)),
  [L1CS] = COMBO(l1cs, OSM(MOD_LCTL|MOD_LSFT)),
  [L1GS] = COMBO(l1gs, OSM(MOD_LGUI|MOD_LSFT)),
  [L2CS] = COMBO(l2cs, OSM(MOD_RCTL|MOD_RSFT)),
  [L2GS] = COMBO(l2gs, OSM(MOD_RGUI|MOD_RSFT)),
  [L3ACUE] = COMBO(l3acue, RALT(KC_E)),
  [L3GRVA] = COMBO(l3grva, GRVA),
  [L3GRVE] = COMBO(l3grve, GRVE),
  [L3GRVU] = COMBO(l3grvu, GRVU),
  [L3CIRA] = COMBO(l3cira, CIRA),
  [L3CIRO] = COMBO(l3ciro, CIRO),
  [L3CIRE] = COMBO(l3cire, CIRE),
  [L3CIRU] = COMBO(l3ciru, CIRU),
  [L3CIRI] = COMBO(l3ciri, CIRI),
  [L3UMLE] = COMBO(l3umle, UMLE),
  [L3UMLU] = COMBO(l3umlu, UMLU),
  [L3UMLI] = COMBO(l3umli, UMLI),
  [L3CEDC] = COMBO(l3cedc, RALT(KC_COMM)),
};

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_A, KC_O, KC_E, KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, KC_SCLN, KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, KC_Z, OSL(3), OSL(2), OSL(1), KC_SPC),
	[1] = LAYOUT_split_3x5_2(KC_GRV, KC_EQL, KC_MINS, KC_PLUS, KC_AMPR, KC_BSLS, KC_SLSH, KC_PERC, KC_LBRC, KC_RBRC, KC_EXLM, KC_QUES, KC_CIRC, KC_DLR, KC_TILD, KC_AT, KC_ASTR, KC_HASH, KC_LPRN, KC_RPRN, KC_NO, KC_NO, KC_UNDS, KC_PIPE, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCBR, KC_RCBR, KC_TRNS, KC_TRNS, TO(0), KC_TRNS),
	[2] = LAYOUT_split_3x5_2(KC_HOME, KC_END, KC_PGDN, KC_PGUP, KC_CAPS, KC_NO, KC_MNXT, KC_MPRV, KC_MPLY, KC_NO, KC_ESC, KC_BSPC, KC_ENT, KC_TAB, KC_DEL, KC_NO, KC_RCTL, KC_RSFT, KC_RGUI, KC_RALT, KC_LEFT, KC_RGHT, KC_DOWN, KC_UP, KC_INS, KC_MUTE, KC_VOLU, KC_VOLD, KC_BRIU, KC_BRID, KC_TRNS, TO(0), KC_TRNS, KC_TRNS),
	[3] = LAYOUT_split_3x5_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_9, KC_5, KC_6, KC_7, KC_8, KC_LALT, KC_LGUI, KC_LSFT, KC_LCTL, KC_NO, KC_0, KC_1, KC_2, KC_3, KC_4, KC_WH_L, KC_WH_R, KC_WH_D, KC_WH_U, KC_NO, KC_PEQL, KC_PPLS, KC_PMNS, KC_PSLS, KC_PAST, TO(0), KC_TRNS, KC_TRNS, KC_TRNS)
};

// layer_state_t layer_state_set_user(layer_state_t state) {
//   return update_tri_layer_state(state, 1, 2, 3);
// }
